# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matita
tagline:             'Thoughts'
description:         'Just a bin for stuff I think/do/postpone.'
url:                 https://matita.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matita
  url:               https://twitter.com/il_matita
  email:             matitald@gmail.com

profiles:
  - name: Twitter
    url: https://twitter.com/il_matita
  - name: LinkedIn
    url: https://it.linkedin.com/pub/matteo-colucci/14/69b/8a0

# Custom vars
version:             1.0.0
