# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matita
tagline:             'Thoughts and experiments'
description:         'Just a bin for stuff I think/do/postpone.'
url:                 http://matita.github.io
baseurl:             ''
paginate:            5

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

# About/contact
author:
  name:              Matita
  url:               https://twitter.com/il_matita
  email:             matitald@gmail.com
  twitter:           @il_matita

profiles:
  - name: Twitter
    url: https://twitter.com/il_matita
  - name: LinkedIn
    url: https://www.linkedin.com/in/matteocolucci

google_analytics: 'UA-66560068-1'

# Custom vars
version:             1.0.0
